#!/bin/bash

echo "🔧 iOS Push Notifications Capability 추가 스크립트"
echo "================================================="
echo ""
echo "⚠️  이 작업은 Xcode에서 수동으로 해야 합니다!"
echo ""
echo "1️⃣  Xcode 열기:"
echo "   cd /Users/scott/workspace/hansl/ios"
echo "   open Runner.xcworkspace"
echo ""
echo "2️⃣  Runner 프로젝트 선택"
echo ""
echo "3️⃣  Signing & Capabilities 탭"
echo ""
echo "4️⃣  + Capability 버튼 클릭"
echo ""
echo "5️⃣  'Push Notifications' 검색 후 더블클릭"
echo ""
echo "6️⃣  'Background Modes' 도 추가"
echo "   - Remote notifications 체크"
echo ""
echo "7️⃣  빌드 후 실제 iPhone에서 테스트"
echo ""
echo "✅ 이 작업을 완료하면 iOS 푸시가 작동합니다!"
echo ""
echo "📝 참고: Firebase APNs 설정과 iOS 알림 권한은"
echo "   이미 완료되었으므로 위 작업만 하면 됩니다."
