#!/bin/bash

echo "🔍 FCM 푸시 알림 문제 진단 스크립트"
echo "=================================="
echo ""
echo "📱 앱 버전: 3.1.3+248"
echo "📅 진단 시간: $(date)"
echo ""

echo "1. 🔑 Firebase 프로젝트 정보 확인"
echo "   - 프로젝트 ID: hansl-attendance"
echo "   - 번들 ID: com.hansl.attendance.v2"
echo "   - GCM Sender ID: 360773211601"
echo ""

echo "2. 🚨 발견된 문제"
echo "   - FCM 전송 실패: 401 UNAUTHENTICATED"
echo "   - APNs 에러: BadEnvironmentKeyInToken"
echo "   - 원인: iOS APNs 인증서 환경 불일치"
echo ""

echo "3. 🔧 해결 방법"
echo ""
echo "   A. Firebase Console에서 APNs 인증서 확인"
echo "      → https://console.firebase.google.com/project/hansl-attendance/settings/cloudmessaging/ios:d8ce25df6a4948ecb9bcf0"
echo "      → Development/Production 환경 설정 확인"
echo ""
echo "   B. 새로운 FCM 토큰 생성"
echo "      1. test@hansl.com 계정으로 앱 재로그인"
echo "      2. 새 FCM 토큰 생성"
echo "      3. 테스트 스크립트 토큰 업데이트"
echo ""
echo "   C. APNs 환경 일치 확인"
echo "      - Development 빌드 → Development APNs"
echo "      - Production 빌드 → Production APNs"
echo ""

echo "4. 🧪 테스트 단계"
echo "   1. Firebase Console에서 APNs 설정 확인"
echo "   2. test@hansl.com으로 앱 재로그인"
echo "   3. node test_fcm_final.js 재실행"
echo "   4. 성공 시 실제 발주 요청으로 검증"
echo ""

echo "5. 📋 확인 사항"
echo "   - 앱이 Production 빌드인가? (3.1.3+248)"
echo "   - Firebase APNs가 Production으로 설정되어 있는가?"
echo "   - test@hansl.com이 app_admin 권한을 가지고 있는가?"
echo ""

echo "✅ 진단 완료. 위 단계를 차례대로 실행하세요."