// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT4QZkm7r8dUyvXm66fFX9Ynd_Me4R8Js',
    appId: '1:360773211601:web:2aa5dcfd88c31721b9bcf0',
    messagingSenderId: '360773211601',
    projectId: 'hansl-attendance',
    authDomain: 'hansl-attendance.firebaseapp.com',
    storageBucket: 'hansl-attendance.firebasestorage.app',
    measurementId: 'G-NR0D3XT5JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWY1VRX329fuQBbbgNeadJphFQuKtfg7A',
    appId: '1:360773211601:android:7e78b65eddd5b8deb9bcf0',
    messagingSenderId: '360773211601',
    projectId: 'hansl-attendance',
    storageBucket: 'hansl-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmV46Y4r40pKgdAB7Vv7BYFLnd7z2sT4I',
    appId: '1:360773211601:ios:161822bffd46fa3bb9bcf0',
    messagingSenderId: '360773211601',
    projectId: 'hansl-attendance',
    storageBucket: 'hansl-attendance.firebasestorage.app',
    iosBundleId: 'com.hansl.attendance.v2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmV46Y4r40pKgdAB7Vv7BYFLnd7z2sT4I',
    appId: '1:360773211601:ios:491971b19d93bc5eb9bcf0',
    messagingSenderId: '360773211601',
    projectId: 'hansl-attendance',
    storageBucket: 'hansl-attendance.firebasestorage.app',
    iosBundleId: 'com.example.hansl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT4QZkm7r8dUyvXm66fFX9Ynd_Me4R8Js',
    appId: '1:360773211601:web:5777c16a0148af68b9bcf0',
    messagingSenderId: '360773211601',
    projectId: 'hansl-attendance',
    authDomain: 'hansl-attendance.firebaseapp.com',
    storageBucket: 'hansl-attendance.firebasestorage.app',
    measurementId: 'G-NTSQFCYLHB',
  );
}
