-- ============================================================
-- Purchase tables baseline (for fresh local resets)
-- ============================================================
-- 일부 환경에서 과거 구매 테이블 생성 마이그레이션이 누락되어
-- 후속 마이그레이션이 실패하는 문제를 방지한다.

CREATE TABLE IF NOT EXISTS public.purchase_requests (
  id BIGSERIAL PRIMARY KEY,
  requester_name TEXT,
  requester_phone TEXT,
  requester_address TEXT,
  requester_fax TEXT,
  requester_id UUID,
  vendor_id BIGINT,
  vendor_name TEXT,
  contact_id BIGINT,
  request_date DATE,
  delivery_request_date DATE,
  revised_delivery_request_date DATE,
  progress_type VARCHAR(50),
  payment_category VARCHAR(50),
  currency VARCHAR(20),
  unit_price_currency VARCHAR(20),
  total_amount NUMERIC DEFAULT 0,
  po_template_type VARCHAR(50),
  request_type VARCHAR(50) DEFAULT '원자재',
  purchase_order_number TEXT,
  project_vendor TEXT,
  sales_order_number TEXT,
  project_item TEXT,
  middle_manager_status VARCHAR(50) DEFAULT 'pending',
  final_manager_status VARCHAR(50) DEFAULT 'pending',
  middle_manager_approved_at TIMESTAMPTZ,
  middle_manager_rejected_at TIMESTAMPTZ,
  middle_manager_rejection_reason TEXT,
  final_manager_approved_at TIMESTAMPTZ,
  final_manager_rejected_at TIMESTAMPTZ,
  final_manager_rejection_reason TEXT,
  raw_material_manager_status TEXT DEFAULT 'pending',
  raw_material_manager_approved_at TIMESTAMPTZ,
  raw_material_manager_rejected_at TIMESTAMPTZ,
  raw_material_manager_rejection_reason TEXT,
  consumable_manager_status TEXT DEFAULT 'pending',
  consumable_manager_approved_at TIMESTAMPTZ,
  consumable_manager_rejected_at TIMESTAMPTZ,
  consumable_manager_rejection_reason TEXT,
  is_po_download BOOLEAN DEFAULT false,
  is_received BOOLEAN DEFAULT false,
  received_at TIMESTAMPTZ,
  is_payment_completed BOOLEAN DEFAULT false,
  payment_completed_at TIMESTAMPTZ,
  payment_completed_by_name TEXT,
  is_utk_checked BOOLEAN DEFAULT false,
  is_statement_received BOOLEAN DEFAULT false,
  total_expenditure_amount NUMERIC DEFAULT 0,
  delivery_revision_requested BOOLEAN DEFAULT false,
  delivery_revision_requested_at TIMESTAMPTZ,
  delivery_revision_requested_by TEXT,
  created_at TIMESTAMPTZ DEFAULT (now() + interval '9 hours'),
  updated_at TIMESTAMPTZ DEFAULT (now() + interval '9 hours')
);

CREATE TABLE IF NOT EXISTS public.purchase_request_items (
  id BIGSERIAL PRIMARY KEY,
  purchase_request_id BIGINT,
  purchase_order_number TEXT,
  requester_name TEXT,
  line_number INTEGER,
  item_name TEXT,
  specification TEXT,
  quantity INTEGER,
  unit_price_value NUMERIC DEFAULT 0,
  unit_price_currency VARCHAR(20),
  amount_value NUMERIC DEFAULT 0,
  amount_currency VARCHAR(20),
  tax_amount_value NUMERIC DEFAULT 0,
  remark TEXT,
  link TEXT,
  version INTEGER DEFAULT 0,
  is_received BOOLEAN DEFAULT false,
  received_at TIMESTAMPTZ,
  received_date TIMESTAMPTZ,
  actual_received_date TIMESTAMPTZ,
  received_quantity INTEGER,
  received_by UUID,
  received_by_name TEXT,
  delivery_status VARCHAR(50) DEFAULT 'pending',
  delivery_notes TEXT,
  vendor_name TEXT,
  is_payment_completed BOOLEAN DEFAULT false,
  payment_completed_at TIMESTAMPTZ,
  payment_completed_by_name TEXT,
  is_statement_received BOOLEAN DEFAULT false,
  statement_received_date DATE,
  statement_received_by_name TEXT,
  is_utk_checked BOOLEAN DEFAULT false,
  expenditure_date TIMESTAMPTZ,
  expenditure_amount NUMERIC,
  accounting_received_date TIMESTAMPTZ,
  receipt_history JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT (now() + interval '9 hours'),
  updated_at TIMESTAMPTZ DEFAULT (now() + interval '9 hours')
);

CREATE TABLE IF NOT EXISTS public.purchase_receipts (
  id BIGSERIAL PRIMARY KEY,
  receipt_image_url TEXT NOT NULL,
  uploaded_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  uploaded_by_name TEXT,
  uploaded_by TEXT,
  memo TEXT,
  file_name TEXT,
  file_size BIGINT,
  is_printed BOOLEAN DEFAULT false,
  printed_at TIMESTAMPTZ,
  printed_by TEXT,
  printed_by_name TEXT,
  participants TEXT,
  card_last_digits TEXT,
  dining_date DATE,
  expense_amount NUMERIC,
  group_id UUID
);

CREATE INDEX IF NOT EXISTS idx_purchase_requests_po_number
ON public.purchase_requests (purchase_order_number);

CREATE INDEX IF NOT EXISTS idx_purchase_items_request_id
ON public.purchase_request_items (purchase_request_id);
